### ISSUE TITLE
no matches for stable.instaclustr.com/, Kind=CassandraDataCenter

### ISSUE THREAD

**Issue by gilblau** [instaclustr/cassandra-operator#102]
Hi,

Trying to deploy, using the following command:
kubectl create -f test.yaml

I get the following err msg:
error: unable to recognize "test.yaml": no matches for stable.instaclustr.com/, Kind=CassandraDataCenter

**Comment by benbromhead** [comment]
Hi @gilblau 

Have you first installed the Operator, it will automatically create the CassandraDataCenter CRD?

You can either install it via the Helm package in the repo, or via bundle.yaml or rbac-bundle.yaml.

**Comment by benbromhead** [comment]
Hi @gilblau 

Just checking if you are still experiencing this issue?

Ben

**Comment by benbromhead** [comment]
Closing out issue, @gilblau feel free to reopen if needed
