### ISSUE TITLE
Need for client access documentation

### ISSUE THREAD

**Issue by snoopdave** [instaclustr/cassandra-operator#109]
I've got a cluster up and running and I can successfully run nodetool via kubectl exec, but I have not yet figured out how to access the cluster from my application's Pod (via the Datastax Java Driver).  The two services created by cassandra-operator do not have IP addresses. I tried using the service name, but that resulted in java.net.UnknownHostException.

How should a Cassandra client discover the IP addresses to be used to access the cluster?

Also, the README mentions a file called client_service.md, but that file does not exist in the repo:
https://github.com/instaclustr/cassandra-operator/blob/master/doc/user/client_service.md

**Comment by benbromhead** [comment]
Hi @snoopdave 

Sorry for the slow response. You should be able to access the cluster via the automatically created service titled CLUSTER_NAME-cassandra-nodes. This is a headless service that will resolve a list of IPs for each node, most DNS clients that just expect a single IP address will use the first IP returned including the datastax driver. 

For a properly configured container that uses Kubernetes DNS, you can just directly reference the service name and it will resolve the FQDN. 

For example I created a cluster called noprom2 using the in-tree helm package: `helm install helm/cassandra -n noprom2`

Once the cluster was up and running, I then created another pod within the cluster from the same cassandra image to test connectivity from within the kubernetes cluster, but outside of the cassandra cluster. 

cluster-shell.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  containers:
  - name: cmd
    image: gcr.io/cassandra-operator/cassandra-dev:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10;done"]
```
I created the pod via `kubectl apply -f cluster-shell.yaml` You should end up with something like:

```
kubectl get pods
NAME                            READY     STATUS    RESTARTS   AGE
cassandra-noprom2-cassandra-0   2/2       Running   0          20m
shell-demo                      1/1       Running   0          14m
```

I then created a shell session in the pod `kubectl exec -it shell-demo -- /bin/bash`

From the shell session, I checked DNS resolution:
```
root@shell-demo:/# ping cassandra-noprom2-cassandra-nodes
PING cassandra-noprom2-cassandra-nodes.default.svc.cluster.local (172.17.0.5) 56(84) bytes of data.
64 bytes from 172.17.0.5 (172.17.0.5): icmp_seq=1 ttl=64 time=0.035 ms
64 bytes from 172.17.0.5 (172.17.0.5): icmp_seq=2 ttl=64 time=0.059 ms
64 bytes from 172.17.0.5 (172.17.0.5): icmp_seq=3 ttl=64 time=0.063 ms
^C
--- cassandra-noprom2-cassandra-nodes.default.svc.cluster.local ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2065ms
rtt min/avg/max/mdev = 0.035/0.052/0.063/0.013 ms
root@shell-demo:/# exit
```

I then connected to the cluster via cqlsh:
``` 
root@shell-demo:/# cqlsh cassandra-noprom2-cassandra-nodes
Connected to noprom2-cassandra at cassandra-noprom2-cassandra-nodes:9042.
[cqlsh 5.0.1 | Cassandra 3.11.2 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh>
```

If you are having trouble connecting via the *-cassandra-nodes service from within the kubernetes cluster, first make sure the service name is actually resolving. Once it's resolving properly, check network acls and policies (if you have any), if that all looks fine and you can ping the container via the service name we can dig into any issues Cassandra itself is having

**Comment by benbromhead** [comment]
Hi @snoopdave 

We haven't heard any further update of the issue, feel free to reopen the issue if you are still experiencing it.

Ben

**Comment by snoopdave** [comment]
Thanks @benbromhead. I have not had a chance to try this out, but I will once I get back to my Cassandra work.
