### ISSUE TITLE
FailedScheduling - pod has unbound PersistentVolumeClaims

### ISSUE THREAD

**Issue by nkrendel** [instaclustr/cassandra-operator#112]
Hi, I'm trying to deploy this operator to a AWS EKS cluster.  I am using the examples/common/test.yaml to create a test cluster, but the pods never become active because of unbound PVCs:

```
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  5s (x5 over 12s)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 4 times)
```
I'm not sure if I'm supposed to configure the dataVolumeClaim somehow, or if is supposed to configure itself?!

**Comment by benbromhead** [comment]
iirc AWS EKS clusters are not created with any storage classes by default. So stateful sets won't be scheduled until there are volumes they can use.

Check out https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html for more details.

If you have configured storage and are still getting the issue let me know.

**Comment by nkrendel** [comment]
yep that worked!  just had to add a 'storageClassName'.  Thanks!
