### ISSUE TITLE
Allow running on unprivileged clusters

### ISSUE THREAD

**Issue by zegelin** [instaclustr/cassandra-operator#116]
Trying to run the operator/cassandra on an unprivileged cluster results in an error.

```create Pod cassandra-test-cluster-cassandra-0 in StatefulSet cassandra-test-cluster-cassandra failed error: Pod "cassandra-test-cluster-cassandra-0" is invalid: spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy ```

Maybe we can make the init container optional?

**Comment by benbromhead** [comment]
We need to run a privileged container to configure certain OS options that will allow Cassandra to run in a reliable manner. 

We can certainly make it optional, but it will make Cassandra more likely to break.

**Comment by alourie** [comment]
@zegelin following from #208, will work on this soon. Will restore the `privelegedSupported` functionality and whatever else will be needed here.

**Comment by alourie** [comment]
`privilegedSuppored` functionality is restored by #218
