### ISSUE TITLE
Cannot deploy Cassandra operator on OKD

### ISSUE THREAD

**Issue by rimolive** [instaclustr/cassandra-operator#132]
I am trying to deploy Cassandra on OKD (okd.io) which has k8s 1.11 but the pod is failling with the following message:

```
[main] WARN  c.i.c.operator.K8sVersionValidator - The cassandra-operator has not been validated to work on this version of Kubernetes.
```

**Comment by zegelin** [comment]
Hi @rimolive. That message is a warning hinting that the build of the operator that you're running hasn't yet been tested to work with the version of K8s your using (1.11). For newer versions of K8s its typically okay to ignore this warning.

You say that the operator is failing. Are there any other error messages or items in the log?

**Comment by rimolive** [comment]
The first strange thing is when I run `oc create -f examples/common/test.yaml`, which returns the following message:
```
error: unable to recognize "examples/common/test.yaml": no matches for stable.instaclustr.com/, Kind=CassandraDataCenter
```
Then the pod logs always return the following:
```
10:32:44.001 [main] INFO  com.instaclustr.build.Info - Version built from upstream repo [git@github.com:instaclustr/cassandra-operator.git] on branch [master] using commit: [28f6314]
--
  | 10:32:50.696 [main] WARN  c.i.c.operator.K8sVersionValidator - The cassandra-operator has not been validated to work on this version of Kubernetes.
  | 10:32:56.691 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Creating Custom Resource Definition cassandra-datacenters.stable.instaclustr.com
  | Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.instaclustr.cassandra.operator.Operator@708400f6): io.kubernetes.client.ApiException: Forbidden
  | at picocli.CommandLine.execute(CommandLine.java:880)
  | at picocli.CommandLine.access$700(CommandLine.java:111)
  | at picocli.CommandLine$RunLast.handle(CommandLine.java:1037)
  | at picocli.CommandLine$RunLast.handle(CommandLine.java:1005)
  | at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:913)
  | at picocli.CommandLine.parseWithHandlers(CommandLine.java:1196)
  | at picocli.CommandLine.call(CommandLine.java:1448)
  | at picocli.CommandLine.call(CommandLine.java:1413)
  | at com.instaclustr.cassandra.operator.Operator.main(Operator.java:83)
  | Caused by: io.kubernetes.client.ApiException: Forbidden
  | at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
  | at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
  | at io.kubernetes.client.apis.ApiextensionsV1beta1Api.createCustomResourceDefinitionWithHttpInfo(ApiextensionsV1beta1Api.java:155)
  | at io.kubernetes.client.apis.ApiextensionsV1beta1Api.createCustomResourceDefinition(ApiextensionsV1beta1Api.java:140)
  | at com.instaclustr.cassandra.operator.preflight.operations.CreateCustomResourceDefinitions.createCrdFromResource(CreateCustomResourceDefinitions.java:44)
  | at com.instaclustr.cassandra.operator.preflight.operations.CreateCustomResourceDefinitions.run(CreateCustomResourceDefinitions.java:28)
  | at com.instaclustr.cassandra.operator.preflight.Preflight.call(Preflight.java:27)
  | at com.instaclustr.cassandra.operator.Operator.call(Operator.java:124)
  | at com.instaclustr.cassandra.operator.Operator.call(Operator.java:30)
  | at picocli.CommandLine.execute(CommandLine.java:873)
  | ... 8 more
  | 10:32:56.994 [main] ERROR c.i.c.operator.preflight.Preflight - Preflight operation com.instaclustr.cassandra.operator.preflight.operations.CreateCustomResourceDefinitions@4cf8b2dc failed to execute.
```

If possible, it would be good create a specific doc on deploying Cassandra operator on OKD since there are some particular things that makes deployment different than in k8s.

**Comment by benbromhead** [comment]
Hi Rimolive 

It appears that the user that the operator is installed under does not have permissions to create the required CRDs. For more robust permission/installation I would invite you to look at the included helm packages as they will create the required service accounts. 

If you can't use helm in your environment, you can still use helm to generate the required yaml via the cli's `helm template` function (there are no server dependencies). See https://github.com/instaclustr/cassandra-operator/blob/master/doc/op_guide.md for better instructions. 

In the meantime we will look at creating a guide for OKD/Openshift or you are welcome to contribute one as well!

**Comment by rimolive** [comment]
@zegelin @benbromhead Do you have a public channel to discuss about the operator? I'd like some help to build the operator.

**Comment by benbromhead** [comment]
Currently we just run everything through github issues. We should/could probably turn on gitter or something at some point. For the moment, feel free to just ask through an open issue.

**Comment by rimolive** [comment]
Alright, thanks! I'm trying to build the images but the base-openjre fails. I'm using make to build them and I noticed that the base-openjre Makefile does not define a DOCKER_REPO env var:

https://github.com/rimolive/cassandra-operator/blob/master/docker/base-openjre/Makefile#L1-L3

I don't know if make expects I define this env var manually or if it is a bug in the Makefile. What do you think?

**Comment by benbromhead** [comment]
You will want to define the base repo as an env var before running make e.g.

`ben@~/git/cassandra-operator $ REPO=gcr.io/cassandra-operator make`

We might also slightly change the way you pass in the repo to require a trailing slash, that way when you build without a specific repo it won't matter.

**Comment by benbromhead** [comment]
cc @zegelin

**Comment by benbromhead** [comment]
You might also need to make sure your master branch is up to date! We have been fixing a number issues related.

**Comment by benbromhead** [comment]
Closing issue as haven't had an update in a while.
