### ISSUE TITLE
Use other build commands for Images

### ISSUE THREAD

**Issue by rimolive** [instaclustr/cassandra-operator#147]
I am building operator code on Fedora, and as Docker in Fedora is another distribution and there is another builder that is OCI compliant, there should be a way to make builds check for this other command and run accordingly.

**Comment by zegelin** [comment]
Support for alternate build systems is, at this time, not a high priority for the project. That said, we'd be grateful if you could provide suggestions, advice or even a PR that adds this functionality.

**Comment by benbromhead** [comment]
Closing issue and tracking via PR #150
