### ISSUE TITLE
EmptyDir as a storage option?

### ISSUE THREAD

**Issue by isaacreath** [instaclustr/cassandra-operator#165]
I've started using the operator for use cases where data persistence after a pod dies isn't really a requirement (for example, running stress tests). On bare metal clusters where creating a PVC means manually creating/deleting persistent volumes, it's been very convenient to use an EmptyDir volume for these use cases. I've implemented this in my own fork of the operator by using an EmptyDir as a default where there was no dataVolumeClaim specified.

Is there any interest in having this as part of the upstream operator?

**Comment by benbromhead** [comment]
Definitely! We would love to see the pull request come in. 

We are also looking at having the operator automatically clean up pvc (configurable)
