### ISSUE TITLE
is resize working already?

### ISSUE THREAD

**Issue by jakaka12** [instaclustr/cassandra-operator#168]
I followed the documentation to scale my cluster up from 3 nodes to 5, and back down as well. In both cases, with and without helm, I am only able to scale up and down by 1 node regardless of what I set my `replicas` value to. I don't see any errors or failures in the operator logs, and the statefulset desired number is only one more or less than the original node count. 

From the documentation it looks like I should be able to scale the size of the cluster by more than 1 node at a time. Is this functionality supported? Should I be looking at other logs?

**Comment by zegelin** [comment]
How long are you waiting for the scaling operation to complete?

When you change the `CassandraDataCenter` `replicas` field, the operator will _safely_ scale the Cassandra cluster. When scaling up, it waits for each node to finish joining before adding the next. On scale-down, the operator will wait for decommissioning to complete.

As a result, the observed behaviour is that the StatefulSet will only resize one-at-a-time, but should eventually have the desired number of replicas.

**Comment by jakaka12** [comment]
How long is eventually? The cluster doesn't have any data in it yet, and it is taking over 19 hours to add 2 nodes to a 3 node cluster. I will keep monitoring, but if there is an expected time frame for a cluster with no data, I'll have a better sense of how long I should wait before I see that 5th node. Thanks.

**Comment by benbromhead** [comment]
It shouldn't take that long. What do the logs for the joining cassandra node say and the existing nodes say?

You can get this via `kubectl logs _podname_ cassandra`

**Comment by jakaka12** [comment]
Logs from existing nodes:
```
INFO  [HANDSHAKE-/10.200.26.55] OutboundTcpConnection.java:561 Handshaking version with /10.200.26.55
INFO  [GossipStage:1] Gossiper.java:1055 Node /10.200.26.55 is now part of the cluster
INFO  [RequestResponseStage-1] Gossiper.java:1019 InetAddress /10.200.26.55 is now UP
INFO  [HANDSHAKE-/10.200.26.55] OutboundTcpConnection.java:561 Handshaking version with /10.200.26.55
```
Logs from joining node look the same as the startup logs from the other existing nodes:
```
INFO  [main] Gossiper.java:1723 No gossip backlog; proceeding
INFO  [main] NativeTransportService.java:70 Netty using native Epoll event loop
INFO  [main] Server.java:155 Using Netty Version: [netty-buffer=netty-buffer-4.0.44.Final.452812a, netty-codec=netty-codec-4.0.44.Final.452812a, netty-codec-haproxy=netty-codec-haproxy-4.0.44.Final.452812a, netty-codec-http=netty-codec-http-4.0.44.Final.452812a, netty-codec-socks=netty-codec-socks-4.0.44.Final.452812a, netty-common=netty-common-4.0.44.Final.452812a, netty-handler=netty-handler-4.0.44.Final.452812a, netty-tcnative=netty-tcnative-1.1.33.Fork26.142ecbb, netty-transport=netty-transport-4.0.44.Final.452812a, netty-transport-native-epoll=netty-transport-native-epoll-4.0.44.Final.452812a, netty-transport-rxtx=netty-transport-rxtx-4.0.44.Final.452812a, netty-transport-sctp=netty-transport-sctp-4.0.44.Final.452812a, netty-transport-udt=netty-transport-udt-4.0.44.Final.452812a]
INFO  [main] Server.java:156 Starting listening for CQL clients on cassandra-scale-test-cluster-cassandra-3.cassandra.columnarstore.svc.cluster.local/10.200.26.55:9042 (unencrypted)...
INFO  [main] CassandraDaemon.java:529 Not starting RPC server as requested. Use JMX (StorageService->startRPCServer()) or nodetool (enablethrift) to start it
```
Healthcheck from the operator is normal for all the 4 nodes and nodetool status also shows all nodes up and normal.

**Comment by benbromhead** [comment]
Thanks for that, which version of the operator images are you currently deploying? If you can provide the image name. Also in the operator logs it should log the version and git hash

**Comment by jakaka12** [comment]
```
INFO  [main] c.i.cassandra.operator.Operator: cassandra-operator version: cassandra-operator 1.0-SNAPSHOT, Build time: 2019-05-07T01:01:37+0000, Git commit: f615f6778d0be307bbf82e15611f10bbfd952cac
```
From values.yaml (using helm)
```
image:
  repository: gcr.io/cassandra-operator/cassandra-operator
  tag: latest
  pullPolicy: IfNotPresent
```

**Comment by zegelin** [comment]
@jakaka12 Please post the whole operator log. I'd like to see in more detail what it's doing.

Also, what environment is this running on? GKE? Minikube?

**Comment by jakaka12** [comment]
Sorry, that was a different one that I was testing. Here are full operator logs from Minikube.
[operator.log](https://github.com/instaclustr/cassandra-operator/files/3193027/operator.log)

**Comment by benbromhead** [comment]
Thanks, see #170 which should fix your issue!

**Comment by jakaka12** [comment]
Thanks @benbromhead. The latest merges to master seem to have fixed the issue.

**Comment by jakaka12** [comment]
@benbromhead , @zegelin, Is there a slack channel or support thread instead of creating more issues for these types of questions?

**Comment by zegelin** [comment]
@jakaka12 not currently. We're happy to answer questions via GiHub issues at this time.
