### ISSUE TITLE
Port Prometheus support

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#180]
The java based operator supports configuring Cassandra to expose metrics in a prometheus friendly manner (see instaclustr/cassandra-exporter). The operator also supports automatic discovery of new clusters and nodes within prometheus.

We need to ensure the operator-sdk versions supports this workflow

**Comment by alourie** [comment]
Closed via #294 as https://github.com/instaclustr/cassandra-operator/commit/78af1dee5ffe556e2b31dafe8c3251cb3385c15a
