### ISSUE TITLE
Support maintenance operations

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#181]
We need to support a basic workflow that allows the operator to perform specific maintenance operations such as cleanup and rebuild.

The workflow should allow users to manually do these operations on the node (e.g. via the sidecar api) as well as the operator doing these after normal operations. E.g. performing a repair then cleanup after scaling down.

Key operations to support include:

- cleanup
- rebuild
- scrub
- upgradesstables

**Comment by smiklosovic** [comment]
Just for clarification, it seem we will do that via Sidecar from operator and Sidecar would do that via JMX against Cassandra.

Hence, clearly, we need a Go client part for that, possibly Sidecar sending any JSON body with some metadata how to do that (e.g. what keyspace to rebuild with other possible options and so on).

**Comment by benbromhead** [comment]
Sidecar will take care of JMX interop, so yeah it will be somewhat of a Operator ->JSON/HTTP reg to sidecar -> sidecar translates to JMX call -> jmx call to C*

**Comment by benbromhead** [comment]
Rebuild and scrub probs not needed for initial release in the sidecar

Users can still run these via kubectl exec... if needed

**Comment by smiklosovic** [comment]
All operations are implemented here 

https://github.com/smiklosovic/cassandra-operator/tree/operation-upgradesstables

This can go in after @zegelin implements / improves OperationRequest validation as agreed privately.

This lacks tests, we can do them in separate PR, the most probably based on Python + CCM.
