### ISSUE TITLE
Provide CRD definition as part of the helm package

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#189]
Problem:
When setting up a service that depends on Cassandra via a Helm package, users cannot install the operator and define a Cassandra cluster at the same time. For example in a helm package. This is because we have the operator install the CRD rather than the helm package for the operator.

Solution:
it may make sense to provide the CRD definition separately as part of the operator helm so it makes dependency resolution easier. Helm can then install the CRD definition before other components ensuring that a helm package with a Cassandra dependency works. The operator should still continue to check that the CRD is installed and install it if it isn't, but we should also let Helm install the definition if it needs/wants to

**Comment by benbromhead** [comment]
An example of Helm charts with potential Cassandra dependencies would be Kong or Cortex

**Comment by smiklosovic** [comment]
I think this is already targeted in Helm 3.0 where there is a special directory called `crds` so Helm will install that before anything else happens.
