### ISSUE TITLE
Custom Seed provider for Kubernetes

### ISSUE THREAD

**Issue by ameyb** [instaclustr/cassandra-operator#2]

**Comment by zegelin** [comment]
Implementation is simple for now, but does a resolve on a given k8s service name and uses all returned IPs as seeds. The operator creates a seed-node specific service which is restricted to a subset of all created pods.

**Comment by DBarthe** [comment]
Hello,

I have one interrogation about the current seed discovery mechanism. Not sure if it's better to open a new issue... 

Today, all nodes are seeds nodes (DNS resolution of the headless service with `tolerate-unready-endpoints` annotation returns all POD_IP of the statefulset, even unready pods).

That means when the datacenter is scaled up, the new node will consider itself as a seed and therefore will not bootstrap any data. With a RF=1, this results in losing data.

That's my understanding of cassandra but feel free to correct me if I'm wrong.

**Comment by zegelin** [comment]
Good catch. Yes, we're currently setting all nodes as seeds, which does result in any new nodes not automatically bootstrapping.

Open to suggestions on how to limit the number of seeds/how to pick them.

**Comment by benbromhead** [comment]
Can we annotate a subset of nodes in a stateful set? E.g. just the first two and create a seeds service?

Otherwise maybe change the seed provider to just grab the first X addresses from a dns record that returns multiples. Then for multi-dc we just pass in multiple service names, but it only grabs the first two (or X) for each:?

**Comment by DBarthe** [comment]
For simplicity, I added the label selector : `statefulset.kubernetes.io/pod-name=elasandra-dcName-0` on the seeds service. It works with only 1 seed per DC.

Unfortunately, I found that service selector does not support "or" semantics for labels, and statefulset does not allow to add a specific label to a subset of pods. It wouldn't work with more than 1 seed.

Whatever option, the second seed should never consider itself as a seed when it start the first time.

**Comment by smiklosovic** [comment]
@bbromhead @zegelin 

This might be solved quite easilly but I have to admit it looks little bit tricky.

The rule of thumb is to have a seed per rack. We know what rack a node is going to be in when we are provisioning it, in advance.

In a nutshell, the seed provider is resolving "all ips" from seed service and it returns seeds which are trully meant to be used.

Hence we need some kind of a mechanism how to decide if a node which is currently starting and which is executing that seed provider's method is going to be in that list or not.

One straightforward but little bit hacky way to do that is to inject this ip-rack mapping via environment variables or system variables but the problem with that is that it is quite static and it would have to change _somehow_ on nodes restarts etc etc.

The better solution seems to be to call Kubernetes API from within that seed service itself, there is 
 an official Java client for that, so we could just reach e.g. a ConfigMap and that mapping would be there so we could dynamically resolve if a node should be a seed node or not.

**Comment by smiklosovic** [comment]
I ve done it differently like this https://github.com/instaclustr/cassandra-operator/pull/333

We have not been specifying right ServiceName for stateful set so a pod was not even able to ping other pod by their hostname, only by IP.

SeedProvider was rewritten in a such way that it will consider seeds to be only the first nodes in every rack.

This means that as more racks we will be adding and more nodes we add into a cluster as such, each node will have at most "n" seeds as "n" is number of racks.

Obviously, the very first node in a cluster, until restarted, will have one seed, itself. The first node in the second rack will have the first node in the first rack as a seed and itself. The second node in the second rack will have only the first node in the first rack and the first node in the second rack as seed and so on.

If one has just one rack, there will be only one seed per cluster.

By this we are actually trying to suggest people to have deployment on racks as the failure of that seed node would mean that the node could not join.
