### ISSUE TITLE
Switch from dep to Go modules

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#203]
The Go community seems to converge towards Go modules as the standard Go dependency management tool. We should consider switching to Go modules instead of `dep`.

In addition to using the canonical Go way for dependencies, doing the switch has the added benefit of being able to build the operator in any directory, regardless of `GOPATH`, which makes for a nicer user experience, especially for people who are new to Go.

Right now there is a problem somewhere along the dependency tree which prevents us from easily switching to Go modules:

```
git clone git@github.com:instaclustr/cassandra-operator.git
cd cassandra-operator
git checkout superdupertopsecretrewrite
go mod init
go build cmd/manager
```

Result:

```
go: github.com/go-resty/resty@v1.12.0: parsing go.mod: unexpected module path "gopkg.in/resty.v1"
```

Appending `replace github.com/go-resty/resty => gopkg.in/resty.v1 v1.12.0` go `go.mod` following the workaround suggested in https://github.com/go-resty/resty/issues/230#issuecomment-467911306 causes the following error:

```
go: gopkg.in/resty.v1@v1.12.0 used for two different module paths (github.com/go-resty/resty and gopkg.in/resty.v1)
```

The above is probably caused by the fact that `go-resty`'s import path got changed in `v2.0.0` and we have both the old and the new version in the dependency tree.

We can probably address this by updating the problematic dependency to a newer version which hopefully uses the new import path for `go-resty`. I'm not investigating this further right now - we can decide to put more effort on it later.

**Comment by zegelin** [comment]
> In addition to using the canonical Go way for dependencies, doing the switch has the added benefit of being able to build the operator in any directory, regardless of GOPATH, which makes for a nicer user experience, especially for people who are new to Go.

This tripped me up badly when getting into this rewrite and Go for the first time.

Perhaps this means that all the Go code can also sit under a `go/` directory, rather than in the project root, ala the Java code?

**Comment by johananl** [comment]
>Perhaps this means that all the Go code can also sit under a go/ directory, rather than in the project root, á la the Java code?

It's possible, though not very common in Go projects.

Do we expect both Go code and Java code to coexist in this repository once the rewrite is done? If we don't, then I guess we don't need to think about `go/`. If we do, I believe the remaining Java code will be the **sidecar**, in which case we should maybe think about moving the sidecar to a separate repository (which would also solve the issues we have with Dockerfiles in non-root directories).

**Comment by jeevatkm** [comment]
@johananl FYI, above mentioned approach will not work for Resty v2 release.  

Please refer to release notes https://github.com/go-resty/resty/releases/tag/v2.0.0 at `Breaking Changes - Migrating v1.x to v2`

Also refer to readme at https://github.com/go-resty/resty#installation and usage section. 

Thanks!

**Comment by johananl** [comment]
Hi @jeevatkm. Thanks for responding here! :-)

>above mentioned approach will not work for Resty v2 release

Which approach? Any idea what I'm doing wrong and how to fix it?

**Comment by smiklosovic** [comment]
we updated to Go modules as part of this PR

https://github.com/instaclustr/cassandra-operator/pull/229
