### ISSUE TITLE
Wrong signal handling leads to slow pod termination

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#212]
The `cassandra` and `sidecar` containers in the pods created by the operator aren't currently handling Linux signals. This has the following implications:

- The application doesn't have a chance to perform cleanup operations, assuming any are defined.
- Pod termination takes an unnecessarily long time.

This is usually caused by one of the following:

- Using `ENTRYPOINT "/my-script"` instead of `ENTRYPOINT ["/my-script"]`.
- Running the application as a child process in the entrypoint script instead of using `exec`.
- Executing the application in a subshell.

I've fixed the problem with `sidecar` in https://github.com/instaclustr/cassandra-operator/pull/211. ~I am still trying to figure out what's causing the issue in the `cassandra` container. Will open another PR when done.~

**Update:** I was using `gcr.io/cassandra-operator/cassandra:3.11.3`. The problem has been fixed in https://github.com/instaclustr/cassandra-operator/commit/7333b6b48b6a455ea648a73f1cb7b1beee27c8f1 and Cassandra is running as PID 1.

In general it may not be the best idea to run the application as PID 1, but it is probably better than not handling signals. We may want to open a follow up issue for running something like [dumb-init](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html) as PID 1.

**Comment by zegelin** [comment]
Base on our experience, Java apps behave correctly when running as PID 1, as Java explicitly installs signal handers for most signals, rather than relying on the defaults (which IIRC _don't_ get installed automatically if the PID is 1).

Having C* and sidecar run as PID 1 should work fine.

**Comment by johananl** [comment]
Great, then we just need to merge #211 and we can close this.

**Comment by johananl** [comment]
#211 is merged. Closing.
