### ISSUE TITLE
Add PodSecurityPolicies to deployment examples

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#225]
It is a good practice to include PSPs with the deployment examples. This makes it easier for cluster administrators to use the operator on clusters with strict security enforcement, and there is no harm in applying PSPs also on clusters which don't require tight security.

There are two "levels" of PSPs we should consider for the operator:

1. A PSP for the operator itself.
1. A PSP for the pods created by the operator.

https://github.com/instaclustr/cassandra-operator/pull/216#issue-302212583 contains a sample PSP for pods created by the operator, as well as sample RBAC manifests for allowing the pods to use the PSP. We should keep in mind that https://github.com/instaclustr/cassandra-operator/pull/219 was merged in the meantime so we most likely can tighten the PSP further as we now run as non-root.

## TODO

- [x] Add a PSP and sample RBAC manifests for the operator.
- [x] Add a PSP and sample RBAC manifests for C* pods.
- [ ] Add documentation.

**Comment by smiklosovic** [comment]
FYI I have already merged PSP into superduper (for operator). If I get that right, now PSP for Cassandra (pods created by operator) should follow.

**Comment by johananl** [comment]
Great.

>If I get that right, now PSP for Cassandra (pods created by operator) should follow.

Correct. I'm currently contemplating where to commit the "resource PSPs" and how to name them. They are not directly related to the manifests [here](https://github.com/instaclustr/cassandra-operator/tree/superdupertopsecretrewrite/deploy), and in addition I don't want to create confusion by having two similar-looking PSPs.

**Comment by smiklosovic** [comment]
in the meanwhile putting them under `deploy` would do it, we could just differentiate them by filename

**Comment by smiklosovic** [comment]
@johananl what is the progress here? lets finish this stuff just after other things on the table ...

**Comment by benbromhead** [comment]
PSP added for helm chart in #258

**Comment by johananl** [comment]
Following https://github.com/instaclustr/cassandra-operator/pull/269, we may want to add two sets of PSPs for the C* pods: one for "normal mode" and another for "kernel tweaks mode".

**Comment by alourie** [comment]
We might want to keep the PSP examples in the examples directory, this way all examples are placed in the same spot.

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-operator/pull/275

**Comment by smiklosovic** [comment]
Closing, documentation will be added separately.
