### ISSUE TITLE
Unused code in cassandradatacenter?

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#228]
It seems like the following code isn't used anywhere:

https://github.com/instaclustr/cassandra-operator/blob/84737bdf33c7b1b7d39732d626e47081550c84b1/pkg/controller/cassandradatacenter/ports.go#L12-L18

Can we get rid of this source file?

**Comment by zegelin** [comment]
I think I was in the middle of trying to clean up and centralise port definitions between the container, the statefulset and the services. But it didn’t get finished.
