### ISSUE TITLE
Write documentation for the Go version of the operator

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#236]
It looks like we don't have documentation for the Go version of the operator. At the very least, I think we should have the following:

- A **simple** quickstart guide with a few one-liners which a user can copy and paste as-is into a shell to get a working operator which successfully creates Cassandra clusters. This guide should **just work**, and should prefer simplicity and stability over completeness or best-practice. Its purpose is to allow a new user to quickly get a first impression and experiment with the operator.
- A reference guide showing and explaining all the available configuration options for both the operator and the CRs. Here we should emphasize completeness, i.e. all supported config options should be listed here. This document can optionally include in-depth sections about tricky topics.
- A document with required tweaks and best practices for production-ready deployments. This should be an advanced guide for users who are already somewhat invested in the operator and are willing to dedicate time to getting the best out of it.
- A developers guide which shows how to deterministically build, test and deploy the operator to a dev cluster. Ideally, building the operator should be as simple as running `make`.

**Comment by smiklosovic** [comment]
Very good initiative. I agree wit all points. I would leave this for a while after backup / restores are finished with certificates thingy and after that we do big overhaul in documentation.

**Comment by benbromhead** [comment]
see #259 for updates to existing docs - start of the process
