### ISSUE TITLE
Make deploy directory work as-is

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#240]
Ideally we should be able to deploy the operator to a cluster using something like the following:

```
kubectl apply -f deploy/crd
kubectl apply -f deploy
```

At the moment we have things which make the above not work:

- `operator.yaml` has `image: REPLACE_IMAGE` instead of an actual image name. This should either be set to the `:latest` official image, *or* pinned to a specific version and updated as part of releasing a new operator version.
- `deploy/crd/` contains both CRDs and CRs. This directory is generated this way by the SDK, so we should either split the CRDs and CRs to separate directories or specify explicit paths to all of our **CDRs** in the deployment commands in the docs.
- The CRs generated by the operator are dummy and don't work.

Perhaps we should maintain a set of working YAMLs under `examples/`, reference them in the docs and ignore `deploy/`.

**Comment by smiklosovic** [comment]
I was think about this too and what I am missing now is some way to apply all files at once in the right order. If you imagine somebody has pristine clear k8s cluster and he / she wants to apply it all, now one has to apply that file by file (files in deploy dir) and deploy operator at the end of that. (I mean accounts, roles, role binding, psp ...).

Maybe some shell script applying this all at once would be nice with detection what was already applied so we do not apply that anymore (or maybe it does not matter as that operation would be idempotent)

**Comment by johananl** [comment]
Actually the order of applying k8s manifests shouldn't matter normally. K8s defines resources declaratively and *eventually* converges everything to the desired state. Even if, for example, the operator pod is created before the CRDs exist in the API server, the operator should simply crashloop until the CRDs appear, which should be fine.

Additionally, some operators apply CRDs themselves to the API server during startup ([example](https://github.com/coreos/prometheus-operator/blob/d1f2d19573329739513c6c46f6f8cc876173ce29/pkg/prometheus/operator.go#L427)). We may want to think about taking a similar approach. I'm not sure if this is supported by the operator SDK though. I can look into it.

**Comment by smiklosovic** [comment]
> I'm not sure if this is supported by the operator SDK though. I can look into it.
yes, please. I am wondering if they support this. We would still provide crds as files though.

That that approach at the end of your post would be ok too.

**Comment by johananl** [comment]
Tracked in https://github.com/instaclustr/cassandra-operator/issues/247.

**Comment by benbromhead** [comment]
I think for this we should maybe focus on keeping the helm charts up to date, and on check-in / build or whatever we simply run a helm template on the two charts and output the yaml to a single file in deploy. 

The helm charts are all written to be fairly client side and I think that helm3 will head down that path as well. 

That way we are not maintaining configs all over the place

**Comment by DestyNova** [comment]
One thing to consider here is that some clusters are set up without the ability to use helm. When I tested the operator, I manually unhelmed the deployment artifacts which is a bit awkward.

Perhaps we could keep the files as is, but provide a script that generates "clean" deployment manifests on demand?

**Comment by smiklosovic** [comment]
@DestyNova We are thinking about bundling all bits into one yaml to apply so all would be in one file only. What do you think about this approach?

**Comment by alourie** [comment]
We've rewritten the documentation to include specific instructions to install the operator in a helm and the non-helm way, also added `make helm` command to copy the required CRDs into the helm templates. It's all part of the go rework and should be becoming the mainline pretty soon. As such I'm going to close this ticket as further work will be done either as improvements to documentation or as part of the work related to #247
