### ISSUE TITLE
migrate to resty v2

### ISSUE THREAD

**Issue by smiklosovic** [instaclustr/cassandra-operator#242]
There is resty v2 already, released like three weeks ago.

It would be nice to transition to not stay behind.

https://github.com/go-resty/resty/releases/tag/v2.0.0

**Comment by smiklosovic** [comment]
@johananl would be nice to start to work on this one

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-operator/pull/249

**Comment by johananl** [comment]
@smiklosovic sorry, I didn't get to it as we were focused on other things in the past week.
