### ISSUE TITLE
Apply CRDs automatically on operator startup

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#247]
Following [this](https://github.com/instaclustr/cassandra-operator/issues/240#issuecomment-522029484) discussion, we would like to look into applying CRDs automatically on operator startup. This could make the UX nicer and less error-prone and simplify the deployment process.

We may be able to get inspiration from how the Prometheus operator [does](https://github.com/coreos/prometheus-operator/blob/d1f2d19573329739513c6c46f6f8cc876173ce29/pkg/prometheus/operator.go#L427) this.

**Comment by smiklosovic** [comment]
Actually, this is not a good idea. According to this article and guideline 1, and 2, it is better to have it separate and Helm will take care of that.

https://medium.com/@cloudark/kubernetes-operators-and-helm-it-takes-two-to-tango-3ff6dcf65619
