### ISSUE TITLE
Make rack-aware deployment optional

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#251]
At the moment, the `Racks` field in `CassandraDataCenterSpec` is required:

https://github.com/instaclustr/cassandra-operator/blob/b9f785cb7612e108fc4b350feeae7733e0712fe6/pkg/apis/cassandraoperator/v1alpha1/cassandradatacenter_types.go#L17

While definitely useful for production deployments, new users experimenting with the operator may not want/need to worry about pod placement.

I suggest we consider making this parameter optional in order to make sample deployments easier. We should then include a section about rack-aware deployments in the docs in a guide dedicated to production-ready deployments.

**Comment by smiklosovic** [comment]
I am also of an opinion that rack-aware deployment should more optional. It requires people to label nodes to assign pods to and so on which adds additional burden to people who just want to quickly evaluate things.

**Comment by alourie** [comment]
@johananl @smiklosovic I can make that work. Considering how things work currently, the best solution would be to consider an imaginary 1 rack (automatically created/populated) and place all of the nodes there. Would that work for you?

**Comment by smiklosovic** [comment]
yeah, like "rack1" or similar ...

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-operator/commit/e4e34642deb2c2d82c55304ebe79e737bb85e81f

**Comment by johananl** [comment]
SGTM @alourie.
