### ISSUE TITLE
Go Operator Status

### ISSUE THREAD

**Issue by mmonemali** [instaclustr/cassandra-operator#276]
We wanted to check what is the status of the Go operator, is it planned to be the main operator or the java one will still be productioni-zed? We have been playing with the java operator for awhile and made some fixes/tweaks to work for us. We want and would be happy to contribute back to either Go or Java but we want to check with you guys what is the plan going forward?

**Comment by smiklosovic** [comment]
Hi @mmonemali ,

we are glad you find our Cassandra operator useful!

We will switch to Go version in a while. We are about to make that switch quite soon (matter of week(s), but not months). Once that switch happen, we are more than happy to incorporate your contributions so definitely stay tuned.

**Comment by zegelin** [comment]
Hi @mmonemali. Just to expand on what @smiklosovic said: The Go operator (currently located in the `superdupertopsecretrewrite` branch) is where all current development work is occurring, and we will merge that branch into master in the very near future -- essentially discontinuing the Java version.

At this time, all development work on the Java version is frozen, unless a major bug is uncovered.

We will gladly accept feedback, PRs, suggestions, etc  and we're happy to integrate those into the Go codebase moving forward.

**Comment by mmonemali** [comment]
Awesome! We are looking forward to that!

**Comment by smiklosovic** [comment]
Hi @mmonemali 

we just release Go operator, it is already in master hence I am closing this one.
