### ISSUE TITLE
Push images to gcr before switching to golang version

### ISSUE THREAD

**Issue by alourie** [instaclustr/cassandra-operator#287]

**Comment by smiklosovic** [comment]
@benbromhead is this something you have to do? I am not sure how it is pushed there.

**Comment by alourie** [comment]
Actually, I'm somewhat confident that with #288 the merge to master with tag v1.0.0 will build and push the images automatically. So if @benbromhead is keen, we don't really need to do anything....pending the check when we do merge/tag.
