### ISSUE TITLE
Make deployment guides self-contained

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#291]
At the moment we provide some general instructions in [op_guide.md](https://github.com/instaclustr/cassandra-operator/blob/superdupertopsecretrewrite/doc/op_guide.md), then [send](https://github.com/instaclustr/cassandra-operator/blame/superdupertopsecretrewrite/doc/op_guide.md#L44-L46) the user to a different guide to complete some provider-specific actions. In my opinion deployment examples should be self-contained. I would go as far as saying it is reasonable to even have **some** duplication between multiple provider-specific guides if it makes the guide easier to follow. https://github.com/instaclustr/cassandra-operator/pull/290 makes the generic deployment two one-liners so the duplicated part would be absolutely minimal.

I suggest doing one of the following:

- Include the generic section in each provider-specific guide to make each guide self-contained.
- Consolidate the deployment guides to one guide with provider-specific sections as necessary.

**Comment by johananl** [comment]
Adding to the above, if we do have provider-specific guides, having an AWS guide isn't really optional nowadays...

I wonder if we should even have separate guides to begin with. AFAICT the things we mention in the provider-specific guides at the moment are largely generic:

- Using `fsGroup: 999` can most likely be a default on all providers (needs checking).
- Configuring storage classes and PVs shouldn't be handled in the operator's docs but rather stated clearly as a **requirement**. This is the most common approach in operators AFAICT because storage is one thing which varies significantly from provider to provider and is abstracted by k8s. The operator shouldn't care which storage class is used and how the PVs are configured as long as **PVs are supported on the cluster**.

**Comment by alourie** [comment]
@johananl few pointers on this matter. Basically, I started doing separate docs for all the providers, but then we mostly do the same thing for all providers when launching the operator and the clusters, so I used the redirects to not copy it multiple times. Additionally, having the same copy in many docs have this tendency to get out of sync, so I'm not sure it's a good idea.

But more than anything, and taking your suggestions into consideration, I think what we should do here is have 1 guide on installing the operator and the cluster and have separate guides/help pages for handling _prerequisites_ on the providers/environments. As you've mentioned, k8 abstracts the usage here, so when k8 is set up appropriately, there's no difference between providers anymore; but as you might have noticed, there are some specifics on how things should be set up in various providers (i.e. GKE requires some special storage type for this to work).

So I'm going to rework this a bit to simplify things, and will open a PR soon.

**Comment by johananl** [comment]
Yes, if the steps are largely the same then we should consider having one guide. As I suggested:

>Consolidate the deployment guides to one guide with provider-specific sections as necessary.

Here is an example of what I meant:

---

## Installation

To install the operator, do this and that.

>NOTE: On AKS there is a problem you need to handle. See [here]() for more info.

---

In case we do end up keeping separate guides, I'd argue that having an easy to follow, self-contained guide for each provider outweighs the effort of handling the duplication in this case. Furthermore, you can always eliminate duplication by generating common parts of a guide using some templating mechanism.

**Comment by alourie** [comment]
Closed via #293 merge. This includes consolidation of all the operation guides into one single document and providing a requirements session with notes for providers that require additional preliminary steps.
