### ISSUE TITLE
cluster-crd kind typo: CassandraCuster

### ISSUE THREAD

**Issue by DestyNova** [instaclustr/cassandra-operator#295]
While testing the operator in one of our clusters I noticed the CRD kind is "CassandraCuster". It's defined in cluster-crd.yaml.

**Comment by smiklosovic** [comment]
Thanks! Good catch.

**Comment by smiklosovic** [comment]
Can you remind me where you found that? I am grepping our Go branch and I can not find anything.

**Comment by DestyNova** [comment]
Of course -- I wrote the issue on my phone, home now though. It's in [java/operator/src/main/resources/com/instaclustr/cluster-crd.yaml](https://github.com/instaclustr/cassandra-operator/blob/90e48634c130aa9dcc5e70ed7e51f1cdd344e7f3/java/operator/src/main/resources/com/instaclustr/cluster-crd.yaml). Presumably this will be gone anyway when the Go branch merges then.

**Comment by smiklosovic** [comment]
yes, that one will go away.
