### ISSUE TITLE
Add arbitrary label on operator's resources 

### ISSUE THREAD

**Issue by alourie** [instaclustr/cassandra-operator#299]
Currently, we set Prometheus-related labels specifically on a service we create for Prometheus. Potentially it might be useful to be able to place any arbitrary labels on any service, stateful set or pod we create.

**Comment by linki** [comment]
We's re also interested in this feature.

In our clusters we enforce all StatefulSets (and others) to have an `application` label. Having some way to inject custom labels next to the ones the operator uses for its purposes would be very helpful.

**Comment by smiklosovic** [comment]
Hi @linki , thanks for reaching us.

I do not have any problems with this in general but there is a lot of objects we could put labels on so it would be helpful if we together identify what you want to have labels on.

I see it as: 

1) all services
2) stateful set
3) pods
4) containers

I do not think labeling init containers make sense, can we leave them out?

From the implementation POV, there is currently this in spec: 

```
PrometheusServiceMonitorLabels map[string]string `json:"prometheusServiceMonitorLabels,omitempty"
```

I order to make it more "generic", I would rename this field to "objectLabels" and it would be a map of maps, its type would be `map[string]map[string]string`. A key would be "object", a value would be map of labels for that object.

Please let me know if this modeling would make sense for you.

**Comment by smiklosovic** [comment]
Implemented in this PR.

https://github.com/instaclustr/cassandra-operator/pull/321

**Comment by linki** [comment]
@smiklosovic Thank you! This is exactly what we needed.

Especially being able to set labels on the StatefulSet as well as on the PodTemplateSpec helps us a lot.

**Comment by smiklosovic** [comment]
You are welcome @linki !
