### ISSUE TITLE
Running e2e tests locally

### ISSUE THREAD

**Issue by mmonemali** [instaclustr/cassandra-operator#302]
Is there a way to run e2e tests locally now?  Maybe use virtualbox/libvirt for that?
If not we can use this issue to track that, and add some documentations how to actually run the tests.

**Comment by smiklosovic** [comment]
Hi @mmonemali 

please go to the root of this repository and do

`operator-sdk test local ./test/e2e --up-local --namespace default --go-test-flags="-timeout 20m" --debug --verbose`

You might set bigger timeout as it expects to run tests in 10 minutes by default (go test does this by default).

I ll add this information into the documentation too.

Please let me know if you hit any issues with that.

**Comment by mmonemali** [comment]
Thanks @smiklosovic!
