### ISSUE TITLE
Access Cassandra cluster from outside Kubernetes

### ISSUE THREAD

**Issue by mmonemali** [instaclustr/cassandra-operator#307]
Now to use the nodes-service to connect to Cassandra cluster you have to have your application running on the same Kube cluster where the operator is running. To workaround that we create a NodePort service for each Cassandra cluster and use that for external connectivity, this is working fine for us for now but for the long run we don't want to use node port, especially when it comes to cross datacenter clusters.
One thing we want to investigate is having an ingress running on Kubernetes that listens on the default Cassandra port and it takes care of routing traffic to the appropriate Cassandra cluster.
Any thoughts or ideas to tackle this problem?

**Comment by smiklosovic** [comment]
Hey @mmonemali , why not to "expose" the IP of a Cassandra node externally / use "public ip" for that? 

You can use also LoadBalancer service in front and route it a node.

Exposing would be done like:

```
kubectl expose pod cassandra-cassandra-test-rack1-0 --type="LoadBalancer" --name=node1-service --port=9042 --target-port=9042
```

So you can do just this:

```
[smiklosovic@E091-FED ~]$ cqlsh 52.226.147.210
Connected to cassandra-test at 52.226.147.210:9042.
[cqlsh 5.0.1 | Cassandra 3.11.4 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.

```

**Comment by smiklosovic** [comment]
@mmonemali maybe even more clean way is to do it like this:

```
kubectl expose service cassandra-cassandra-test-nodes \
    --port=9042 \
    --target-port=9042 \
    --name=cassandra-service \
    --type=LoadBalancer
```

If you are on Azure, after a while you see this:

```
[smiklosovic@E091-FED ~]$ kubectl describe service cassandra-servce 
Name:                     cassandra-servce
Namespace:                default
Labels:                   ...
Annotations:              <none>
Selector:                 ...
Type:                     LoadBalancer
IP:                       10.0.174.96
LoadBalancer Ingress:     52.188.223.110
Port:                     <unset>  9042/TCP
TargetPort:               9042/TCP
NodePort:                 <unset>  30360/TCP
Endpoints:                10.244.0.7:9042,10.244.1.4:9042,10.244.1.5:9042
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  7m2s   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   6m28s  service-controller  Ensured load balancer
```

So you just access it by `cqlsh 52.188.223.110`. Whole cluster is "hidden"  as 1 IP.

Maybe you want to expose it one by one, in that case, if you connect to that cluster to e.g. from Java, you would specify contact points, per node. In this scenario, you would have basically one contact point and I am not completely sure how would driver route requests ...

**Comment by smiklosovic** [comment]
I have put this documentation into readme as part of this PR 

https://github.com/instaclustr/cassandra-operator/pull/352
