### ISSUE TITLE
Missing resource requests and limits for sidecar container

### ISSUE THREAD

**Issue by linki** [instaclustr/cassandra-operator#319]
The `cassandra-sidecar` container misses definitions for resource requests and limits, [see here](https://github.com/instaclustr/cassandra-operator/blob/v2.2.0/pkg/controller/cassandradatacenter/statefulset.go#L248-L254).

This currently prevents us from using the operator on our clusters, since we enforce the presence of them.

We could add some sane defaults in the code section mentioned above and then later make it configurable in the CRD if necessary.

Let me know what you think.

**Comment by smiklosovic** [comment]
Hey @linki thanks for reaching out.

What do you think about this?

https://github.com/instaclustr/cassandra-operator/pull/320

Would it make the job? You can just specify limits similarly as for Cassandra container.

**Comment by smiklosovic** [comment]
Implemented in this PR.

https://github.com/instaclustr/cassandra-operator/pull/321

**Comment by linki** [comment]
That's exactly what we needed :smiley: Thanks for the quick response!
