### ISSUE TITLE
Which Cassandra Chart is compatable with this operator

### ISSUE THREAD

**Issue by vishnugs** [instaclustr/cassandra-operator#327]
Hi 

Can you let me know if the cassandra chart following is compatabile with this operator ?

Also let me know how it works ?

Regards
Vishnu

**Comment by vishnugs** [comment]
https://github.com/helm/charts/tree/master/incubator/cassandra

**Comment by smiklosovic** [comment]
Hi @vishnugs, no, the chart you sent is not compatible with this operator. There is the documentation for this operator in this repository you are welcome to go over.

**Comment by vishnugs** [comment]
yes i have gone through it. there is a sample yaml file to create cassandra cluster. Isnt there a helm chart for creating the cassandra cluster as well ?

**Comment by smiklosovic** [comment]
Sure, there is, in `helm` directory, here https://github.com/instaclustr/cassandra-operator/tree/master/helm

**Comment by vishnugs** [comment]
Unable to install the above operator from the link 

{"level":"info","ts":1579396947.9827983,"logger":"cmd","msg":"Version: v2.3.0"}
{"level":"info","ts":1579396947.982827,"logger":"cmd","msg":"Go Version: go1.13.5"}
{"level":"info","ts":1579396947.9828343,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1579396947.9828405,"logger":"cmd","msg":"Version of operator-sdk: v0.10.0"}
{"level":"info","ts":1579396947.9830427,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1579396948.0581615,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1579396948.0582087,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1579396948.1095238,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1579396948.1098335,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"cassandrabackup-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1579396948.1639,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"CassandraBackup.cassandraoperator.instaclustr.com","error":"no matches for kind \"CassandraBackup\" in version \"cassandraoperator.instaclustr.com/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/source/source.go:89\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/internal/controller/controller.go:122\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandrabackup.add\n\t/code/pkg/controller/cassandrabackup/cassandrabackup_controller.go:71\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandrabackup.Add\n\t/code/pkg/controller/cassandrabackup/cassandrabackup_controller.go:38\ngithub.com/instaclustr/cassandra-operator/pkg/controller.AddToManager\n\t/code/pkg/controller/controller.go:13\nmain.main\n\t/code/cmd/manager/main.go:115\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1579396948.164106,"logger":"cmd","msg":"","error":"no matches for kind \"CassandraBackup\" in version \"cassandraoperator.instaclustr.com/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/code/cmd/manager/main.go:116\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Comment by smiklosovic** [comment]
The cause is this

`{"level":"error","ts":1579396948.1639,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"CassandraBackup.cassandraoperator.instaclustr.com","error":"no matches for kind "CassandraBackup" in version`

You have to install CRDs first. If you are applying Helm chart, they are part of the package.

Otherwise you have to go to `deploy/crds` and apply all "*_crd.yaml" files.

**Comment by vishnugs** [comment]
$ kubectl create -f deploy/crds/
customresourcedefinition.apiextensions.k8s.io/cassandrabackups.cassandraoperator.instaclustr.com created
customresourcedefinition.apiextensions.k8s.io/cassandraclusters.cassandraoperator.instaclustr.com created
customresourcedefinition.apiextensions.k8s.io/cassandradatacenters.cassandraoperator.instaclustr.com created
unable to recognize "crds/cassandraoperator_v1alpha1_cassandrabackup_cr.yaml": no matches for kind "CassandraBackup" in version "cassandraoperator.instaclustr.com/v1alpha1"
unable to recognize "crds/cassandraoperator_v1alpha1_cassandracluster_cr.yaml": no matches for kind "CassandraCluster" in version "cassandraoperator.instaclustr.com/v1alpha1"
unable to recognize "crds/cassandraoperator_v1alpha1_cassandradatacenter_cr.yaml": no matches for kind "CassandraDataCenter" in version "cassandraoperator.instaclustr.com/v1alpha1"

**Comment by vishnugs** [comment]
how does it manages backup and restore ? also backup location configuration ?

**Comment by smiklosovic** [comment]
@vishnugs backup / restore documentation is here: https://github.com/instaclustr/cassandra-operator/blob/master/doc/backup_restore.md
