### ISSUE TITLE
How to run this operator on K8S 1.16?

### ISSUE THREAD

**Issue by vaibhavkhurana2018** [instaclustr/cassandra-operator#334]
The operator is not working on k8s version 1.16 because StatefulSet has been promoted to `v1/apps`. 

Pod Log: 

```
{"level":"error","ts":1580103640.149981,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"StatefulSet.apps","error":"no matches for kind \"StatefulSet\" in version \"apps/v1beta2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:122\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.add\n\t/code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:68\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.Add\n\t/code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:35\ngithub.com/instaclustr/cassandra-operator/pkg/controller.AddToManager\n\t/code/pkg/controller/controller.go:13\nmain.main\n\t/code/cmd/manager/main.go:115\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

Deprecation Notice: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Code that requires changes(IMO): https://github.com/instaclustr/cassandra-operator/blob/cab13f83a07e7fb2fa6cbd3dd5ce4d9cad23a289/pkg/controller/cassandradatacenter/statefulset.go

Changing the above code directly will break things for the older clusters. Please suggest how we can go forward with this/ if anyone has already sorted this out.

**Comment by bzpython** [comment]
I'm following the tutorial to install the operator and I just ran into this problem as well (using Kubernetes version 1.17.0). Looking forward to a fix :)

`{"level":"error","ts":1580104976.7968016,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"StatefulSet.apps","error":"no matches for kind \"StatefulSet\" in version \"apps/v1beta2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:122\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.add\n\t/code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:68\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.Add\n\t/code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:35\ngithub.com/instaclustr/cassandra-operator/pkg/controller.AddToManager\n\t/code/pkg/controller/controller.go:13\nmain.main\n\t/code/cmd/manager/main.go:115\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}`

**Comment by smiklosovic** [comment]
Hi @vaibhavkhurana2018 , currently, this operator is "pinned down" to Kubernetes 1.14.1. It is built on operator-sdk 0.11.0. Operator SDK 0.11.0 is pinned down to 1.15.4.

I am currently running this operator on Kubernetes 1.17.1 and I do not have any problem with that.

How is it possible that I am about to run it with 1.17.1 which is newer version than your 1.16?

**Comment by smiklosovic** [comment]
Hi @bzpython 

the error you got means that you do not have CRDs installed. 

If you are using helm, they are there ootb.

If you are doing it all manually, they are in this directory, you have to apply them: https://github.com/instaclustr/cassandra-operator/tree/master/deploy/crds

**Comment by bzpython** [comment]
Hi @smiklosovic , thanks for your help :). I am still new to Kubernetes so I may stumble over obvious things here.

I am applying the YAMLs manually instead of using Helm, following the operator's guide here:
https://github.com/instaclustr/cassandra-operator/blob/master/doc/op_guide.md

I have tried applying both the "crds.yaml" originally (as suggested in the operator's guide), and got this error. Just now in response to your suggestion, I did a delete from the crds.yaml file, and instead applied the 3 individual crd yamls from the "crds" directory. (This seems a bit ambiguous to me, as far as I can tell the two sources contain the same set of definitions, or at least define custom resources with the same names.)

But even applying those files, I receive the same error described above when I restart cassandra-operator pod. I'm using kubectl 1.17.1 client and 1.17.0 server, on a Minikube 1.6.2 VM for testing.

Is it possible there is some other configuration I need to change, or a problem with minikube? Thanks again!

**Comment by bzpython** [comment]
This is the full set of errors I receive. At the bottom, after the error text about CRDs I posted above, there is a separate error which only mentions StatefulSets (no matches for kind \"StatefulSet\" in version \"apps/v1beta2\") :

`{"level":"error","ts":1580187961.9238508,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"StatefulSet.apps","error":"no matches for kind \"StatefulSet\" in version \"apps/v1beta2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:122\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.add\n\t/code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:68\ngithub.com/instaclustr/cassandra-operator/pkg/controller/cassandradatacenter.Add\n\t/code/pkg/controller/cassandradatacenter/cassandradatacenter_controller.go:35\ngithub.com/instaclustr/cassandra-operator/pkg/controller.AddToManager\n\t/code/pkg/controller/controller.go:13\nmain.main\n\t/code/cmd/manager/main.go:115\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
{"level":"error","ts":1580187961.9470642,"logger":"cmd","msg":"","error":"no matches for kind \"StatefulSet\" in version \"apps/v1beta2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/code/cmd/manager/main.go:116\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}`

**Comment by smiklosovic** [comment]
I am not sure what is happening, I am not getting these errors on 1.17.2

**Comment by smiklosovic** [comment]
How do you actually run this operator? You just take the image from gcr?

Are you running the latest? gcr.io/cassandra-operator/cassandra-operator:v3.1.0

**Comment by smiklosovic** [comment]
@bzpython @vaibhavkhurana2018 could you give a try now? I have removed these old apis, just grab the `latest`

https://github.com/instaclustr/cassandra-operator/pull/336
