### ISSUE TITLE
Possible infinite loop in SeedsResolver

### ISSUE THREAD

**Issue by DestyNova** [instaclustr/cassandra-operator#356]
Hi! I've been investigating a problem (with the help of @linki) with the 3.11.6 Cassandra operator image. Some of the pods started okay, but a few of the Cassandra containers got stuck at:
```
INFO  [main] GossipingPropertyFileSnitch.java:68 Unable to load cassandra-topology.properties; compatibility mode disabled
```
The healthy pods continued from here with:
```
[main] SeedsResolver.java:64 Discovered 3 seed nodes: [/10.2....]
```
Because the stuck pods never reach this point, the Cassandra endpoint and JMX server are never started, which causes the `sidecar` container to fail repeatedly while attempting to connect to them (lots of "connection refused" messages appear, referencing port 7199 which is the JMX server).

The "stuck" pods seemed to be using a lot of CPU, so I looked through the Cassandra startup process and found one possible place where it could be getting stuck:
https://github.com/instaclustr/cassandra-operator/blob/e44749e83eab79f43027b3952975f4720c47eaa2/java/cassandra-k8s-addons/src/main/java/com/instaclustr/cassandra/k8s/SeedsResolver.java#L31-L44

Unfortunately I wasn't able to prove that it's definitely getting stuck here, and I don't know exactly what values of `serviceName` were good or bad.

We've rolled back to the 3.11.5 image for now and it seems okay. It might be nice to add something like this _not-yet-tested code_ before the `continue` statement to avoid busy-waiting in this situation (and provide some feedback):
```java
  logger.info("Failed to resolve hostnames for service {}... trying again in 1 second.", serviceName);
  try {
    Thread.sleep(1000);
  } catch(InterruptedException e) {
    logger.info("Interrupted!");
  }
```

**Comment by smiklosovic** [comment]
Hello @DestyNova ,

thanks for this issue, I was doing it in a hurry so I put there just while(true) which I really not ideal, I have to admit that.

On the other hand, why it is not resolvable in your case? I would be curious what is going on in your cluster that they are not properly resolved and code moves on.

These issues are very hard to debug but it would be very helpful it you log into that stuck container and manually try to ping some addresses according to javadoc in that seed file.

One common "mistake" is that `serviceName` for that pod has to match name of service which provides these addresses, which is "seed service". 

Would you mind to update to the latest operator as well? I merely remember I was fixing there some issues aroud this lately.

I am not sure why it works in case of 3.11.5 and not in 3.11.6, it seems to me this behaviour is random.

I will add there sleep as you suggest for time being. The most probably tomorrow and I ll ping you here once done.

Regards

**Comment by DestyNova** [comment]
Thank you @smiklosovic for some excellent debugging leads. I'll try to get it back into a broken state tomorrow and investigate further :+1:

**Comment by smiklosovic** [comment]
@DestyNova I think I got that, stay tuned.

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-operator/pull/357

**Comment by smiklosovic** [comment]
@DestyNova grab the latest stuff (tag v5.1.0), I rewrote that, comment here again if it does not work, I l will close this for now.

**Comment by DestyNova** [comment]
Awesome, thanks @smiklosovic -- will try to test this and report back soon.
