### ISSUE TITLE
How to add a nodeSelector or nodeAffinity to the cassandra pods?

### ISSUE THREAD

**Issue by jgoeres** [instaclustr/cassandra-operator#373]
I am trying to control on which nodes the cassandra pods are placed. My first idea was to use a nodeSelector or a node affinity, but alas, this seems not possible with the CassandraDataCenter spec. Am I overlooking something?
I noticed that there is support for adding tolerations, but this unfortunately doesn't work for me, cause I am using EKS with managed node groups that do not support the addition of taints, only labels. (actually, using taints and tolerations would have been my preferred solution to the overall problem that I am trying to solve here... ;-()
Any suggestion on how to best add a nodeSelector to the cassandra operator's statefulsets (that doesn't include patching)?
Any chance that nodeSelectors/nodeAffinities would become a supported feature soon?

**Comment by smiklosovic** [comment]
Hi @jgoeres 

maybe this? 

https://github.com/instaclustr/cassandra-operator/wiki/Custom-configuration#rack-awareness

You can place nodes to "racks" (Cassandra's concept) and you do that based on label 

You can label various things like this too: https://github.com/instaclustr/cassandra-operator/wiki/Custom-configuration#custom-labels-for-created-objects

**Comment by smiklosovic** [comment]
@jgoeres I can add nodeSelector quite easilly, just be aware that you will not be able to specify this "per pod" because pods are scheduled automatically from operator, there just cant be that mapping like "first c* node to this worker, second c* to that worker", it might be done either on rack basis or all nodes in a cluster would have same nodeSelector.

What do you prefer?

**Comment by smiklosovic** [comment]
@jgoeres 
actually, this is already there :)

If you check this yaml:

```
  racks:
    - name: "west1-b"
      labels:
        failure-domain.beta.kubernetes.io/zone: europe-west1-b
```

This "labels" field there is eventually used as nodeSelector. 

Check this:

https://github.com/instaclustr/cassandra-operator/blob/master/pkg/controller/cassandradatacenter/statefulset.go#L170

so rack.labels is a map[string]string and that is used as `NodeSelector` in pod spec ...

So from my side, it is already provided.

**Comment by jgoeres** [comment]
@smiklosovic
Thank you, exactly what I was hoping for. I will give this a try .
While I plan to use different racks for multi-zone support/awareness anyway in a next step, currently I am more concerned to make sure that my cassandra pods go to one EKS node group (which goes across all zones), and not to another. Background is that I want to have one node group for my more or less "static" workloads, without autoscaling enabled. The other will handle "dynamic" workloads, and for that node group I want to enable autoscaling.
