### ISSUE TITLE
helm: Operator only looks for cluster definitions in it's own namespace

### ISSUE THREAD

**Issue by senax** [instaclustr/cassandra-operator#374]
Hi,

The operator only picks up cassandraDataCenter object in it's own namespace. I found the WATCH_NAMESPACE section in the deployment which can be tweaked to make it look elsewhere.

It would be great if this could be done through values.yaml as then we don't need to modify the templates. I'll make a PR for this.

**Comment by smiklosovic** [comment]
@senax I think this boils down to this documentation

https://sdk.operatorframework.io/docs/operator-scope/

So you are trying to do cluster-scoped operator?

Feel free to open a PR! Thanks

**Comment by smiklosovic** [comment]
https://github.com/instaclustr/cassandra-operator/pull/375
