### ISSUE TITLE
Cluster creation fails when using a customConfig map with Kubernetes 1.15 

### ISSUE THREAD

**Issue by jgoeres** [instaclustr/cassandra-operator#376]
We recently needed to add a custom config map (goal: set JVM options, in particular disable the JVM's crappy container support). I modified my helmchart, as part of which we also create the CassandraDatacenter object accordingly and added a section like this plus the corresponding config map:

      userConfigMapVolumeSource:
        name: {{ .Release.Name }}-cassandra-custom-conf
        items:
          - key: custom-jvm-options.conf
            path: jvm.options.d/custom-jvm-options.conf   

This worked fine when I tested this on a minikube running Kubernetes 1.17.x, but failed on EKS with Kubernetes 1.15.x with this message:

    Error: CassandraDataCenter.cassandraoperator.instaclustr.com "test" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"cassandraoperator.instaclustr.com/v1alpha1", "cluster":"test", "datacenter":"dc", "kind":"CassandraDataCenter", "metadata":map[string]interface {}{"creationTimestamp":"2020-05-18T13:37:12Z", "generation":1, "labels":map[string]interface {}{"app":"cassandra"}, "name":"test", "namespace":"test", "uid":"03e6aff0-5174-4583-9e6e-a187032dc17f"}, "spec":map[string]interface {}{"cassandraImage":"myregistry/cassandra-operator/cassandra-3.11.6:v6.2.0", "dataVolumeClaimSpec":map[string]interface {}{"accessModes":[]interface {}{"ReadWriteOnce"}, "resources":map[string]interface {}{"requests":map[string]interface {}{"storage":"10Gi"}}}, "imagePullPolicy":"Always", "imagePullSecrets":[]interface {}{map[string]interface {}{"name":"test-registrysecret"}}, "nodes":1, "optimizeKernelParams":true, "prometheusSupport":true, "resources":map[string]interface {}{"limits":map[string]interface{}{"memory":"4Gi"}, "requests":map[string]interface {}{"memory":"3Gi"}}, "serviceAccountName":"test-cassandra-performance", "sidecarImage":"myregistry/cassandra-operator/cassandra-sidecar:v6.2.0", "sidecarResources":map[string]interface {}{"limits":map[string]interface {}{"memory":"512Mi"}, "requests":map[string]interface {}{"memory":"512Mi"}}, "userConfigMapVolumeSource":map[string]interface {}{"items":[]interface {}{map[string]interface {}{"key":"custom-jvm-options.conf", "path":"jvm.options.d/custom-jvm-options.conf"}}, "name":"test-cassandra-custom-conf"}}}: validation failure list:type in spec.userConfigMapVolumeSource is required

I observed this on v6.2.0 and also on v3.2.0

**Comment by smiklosovic** [comment]
@jgoeres if you changed versions of clusters and versions of this operator, have you also changed API? Try to use API of version of operator you use. This means uninstalling old CRDs and installing the right ones of a version you are on. Maybe that helps.

**Comment by jgoeres** [comment]
I completely replaced the way I installed the operator from 3.2 to 6.2. Where I originally only created CRDs and PSPs beforehand and had the operator in "single namespace mode" also installed by my product helmchart, I now moved the entire operator installation to a dedicated step and use the operator in "cluster mode". I also tested this on a fresh minikube cluster where I downgraded from 1.17.x to 1.15.10, so there should not be any leftovers in the cluster that could cause this.
That aside, both versions have apiVersion v1alpha1, if I am not mistaken.

**Comment by smiklosovic** [comment]
@jgoeres I cant see where the problem is, it boils down to this

```
validation failure list:type in spec.userConfigMapVolumeSource is required
```

but that field is not a list, other list-like fields have that annotation on them, but not this one, which seems to be just right.

**Comment by jgoeres** [comment]
Hi,

I attached a ZIP with the minimal example I created. It contains the CRDs I used (instaclustr-crds-v6.2.0.yaml), the operator setup (instaclustr-operator-minimal-example.yaml) and the cluster setup, including the config map I want to use with the JVM options I need to set (instaclustr-operator-minimal-example-cluster.yaml).
This fails on Kubernetes 1.15, but works on 1.17.
When I comment out this section in 

      userConfigMapVolumeSource:
        name: test-cassandra-custom-conf
        items:
          - key: custom-jvm-options.conf
            path: jvm.options.d/custom-jvm-options.conf


it also works on 1.15
Maybe you can point out the mistake I made here.
THX
J


[cassop-minimal-example.zip](https://github.com/instaclustr/cassandra-operator/files/4651775/cassop-minimal-example.zip)

**Comment by smiklosovic** [comment]
@jgoeres try this, check there is added `type: array`

```
  userConfigMapVolumeSource:
    name: test-cassandra-custom-conf
    type: array
    items:
      - key: custom-jvm-options.conf
        path: jvm.options.d/custom-jvm-options.conf
```

**Comment by jgoeres** [comment]
That actually did it, THX. :-)
Is this documented somewhere so I could have found it?
I have not created my own CRDs yet, so I am no expert, but willing to learn - I cannot see a a property "type" defined for userConfigMapVolumeSource. Can you give me a pointer to some doc describing what this was?
And why is it different between 1.15 and 1.17?

**Comment by smiklosovic** [comment]
yeah it is burried in this section: https://github.com/instaclustr/cassandra-operator/wiki/Accounts,-login-and-SSL#ssl

To answer your questions, I have no idea :)

**Comment by jgoeres** [comment]
@smiklosovic THX again. :-)
