### ISSUE TITLE
How to use sstable tools with a cassandra cluster deployed through the operator?

### ISSUE THREAD

**Issue by jgoeres** [instaclustr/cassandra-operator#377]
Hi,

to debug an issue with accumulating tombstones, we need to run the sstablemetadata tool against our Cassandra clusters (version 3.11.6) set up with the instaclustr operator (version 6.2). We deploy this in various environments (minikube, EKS, EKS multi-rack), and the issue is the same:

- exec'd into the cassandra pod and executed 'sstablemetadata <some keyspace> <some table>'
- We got a first issue, the following exception:

    Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
    org.apache.cassandra.exceptions.ConfigurationException: Expecting URI in variable: [cassandra.config]. Found[cassandra.yaml]. Please prefix the file with [file:///] for local files and [file://<server>/] for remote files. If you are executing this from an external tool, it needs to set Config.setClientMode(true) to avoid loading configuration.
        at org.apache.cassandra.config.YamlConfigurationLoader.getStorageConfigURL(YamlConfigurationLoader.java:80)
        at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:100)
        at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:276)
        at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:191)
        at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:162)
        at org.apache.cassandra.tools.Util.initDatabaseDescriptor(Util.java:38)
        at org.apache.cassandra.tools.SSTableMetadataViewer.main(SSTableMetadataViewer.java:82)

- For a workaround, we set cassandra.config via JVM_OPTS environment variable like this:

    export JVM_OPTS="-Dcassandra.config=file:///usr/share/cassandra/cassandra.yaml"

- Executed 'sstablemetadata <some keyspace> <some table>' again
- Now we got a second issue:

	Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: Invalid partitioner class org.apache.cassandra.dht.Murmur3Partitioner
	Invalid partitioner class org.apache.cassandra.dht.Murmur3Partitioner

- we noticed that there is a dedicated tools project by instaclustr, so we gave this a try. Alas, it seems to be no longer actively maintained. Anway, we copied instaclustr/cassandra-sstable-tools jar to pod (latest release: 3.11.3) + /bin/ic-sstables
- we executed 'ic-sstables <some keyspace> <some table>'
- Got same two issues as before

We are still rather new to cassandra as a whole, so maybe we are doing something fundamentally wrong here. How are we expected to use the various command line tools against a cluster set up with the operator? From our understanding, they have to be run inside the pod as they access the table files directly. Any hints or help appreciated.

Regards

J

**Comment by smiklosovic** [comment]
Hi @jgoeres 

it seems to me you are using older image, I remeber this issue, there was this problem with nodetool as well but I ve fixed it.

```
cassandra@cassandra-test-cluster-dc1-west1-a-0:/usr/bin$ sstablemetadata

usage: Usage: sstablemetadata [--gc_grace_seconds n] <sstable filenames>
Dump contents of given SSTable to standard output in JSON format.
    --gc_grace_seconds <arg>   The gc_grace_seconds to use when
                               calculating droppable tombstones
```

So you can either use 3.11.6:latest and be sure that such image is indeed pulled again (pull policy Always).

**Comment by smiklosovic** [comment]
When it comes to `nodetool`, you can either execute it directly in a container but keep in mind that nothing prevents you from executing it _outside_ of a container, you just point `nodetool` to your node. Understandably, this is highly specific how your networking is done just keep in mind that nodetool can "connect" to your running Cassandra node, it does not have to be physically colocated.

**Comment by jgoeres** [comment]
Hi @smiklosovic 
thanks for you quick response. We recently updated to v6.2.0 (all images, operator, sidecar, and cassandra itself ;-)). Do you remember which version was affected?
That aside, the nodetool actually works when running it inside the pod, but not the sstable tool. At least from my understanding, the sstable tool cannot be run outside because it directly accesses the cassandra database files, right?

**Comment by smiklosovic** [comment]
@jgoeres yes, it seems to be necessary to execute  it directly on the node. I works in my case, I am on 3.11.6:latest, double check that you indeed pulled that image.

**Comment by smiklosovic** [comment]
@jgoeres ok this is strage, I ll take a look.

**Comment by smiklosovic** [comment]
@jgoeres I ve pushed v6.3.0, it should be fixed.

**Comment by jgoeres** [comment]
Perfect, works now. :-)
