### ISSUE TITLE
init container image cannot be changed, is using "latest" tag

### ISSUE THREAD

**Issue by jgoeres** [instaclustr/cassandra-operator#379]
Hi,

I can successfully change the operator, cassandra, and sidecar images to come from our internal registry. Alas, I cannot change the image used as init container, it is always busybox:latest.
While this is "just" the init container, having an external dependency is not nice for prod environments. Further, having "latest" tag gives a bit of "mystery meat" situation (yes, it is "merely" busybox, but still, things can break).

Regards
J

**Comment by smiklosovic** [comment]
What would you like to see here? We should create an image just for this container and push it to gcr.io?

**Comment by jgoeres** [comment]
No, just the option to set the image myself, like I can do with the cassandra and sidecar images. And the pull secret would have to be considered, too, as it also already works for the other two.
Basically, it could like like this in the CassandraDataCenter spec:

apiVersion: cassandraoperator.instaclustr.com/v1alpha1
kind: CassandraDataCenter
metadata:
[...]
datacenter:  dc
cluster: mycluster
spec:
  nodes: 1
  cassandraImage:  _myCassandraImage_
  sidecarImage: _mySidecarImage_
  **initContainerImage: _myInitContainerImage_**
  imagePullSecrets:
    - name: _myPullSecret_
[...]

**Comment by smiklosovic** [comment]
@jgoeres https://github.com/instaclustr/cassandra-operator/wiki/Migration#v640 its out!

**Comment by jgoeres** [comment]
@smiklosovic 
Thanks again, works perfectly. 👍 
If just every open source project had such committed maintainers as you. :-)

**Comment by smiklosovic** [comment]
@jgoeres feel free to reach us at Instaclustr, we are alway happy to help!
