### ISSUE TITLE
Enable basic security with Cassandra Clusters

### ISSUE THREAD

**Issue by ameyb** [instaclustr/cassandra-operator#4]
Basic RBAC with Cassandra admin role

**Comment by benbromhead** [comment]
With #81 we should now be able to support enabling auth and encryption. Better/easier support should get baked in, but for the moment it is achievable via user-defined config.

**Comment by smiklosovic** [comment]
Auth can be done like specified here (1), ootb, you dont get any auth but you can switch to whatever auth you want.

(1) https://github.com/instaclustr/cassandra-operator/blob/master/doc/auth.md#auth
