### ISSUE TITLE
[BUG] PVC can be accidentally deleted when controller reads stale data from apiserver

### ISSUE THREAD

**Issue by srteam2020** [instaclustr/cassandra-operator#402]
**Describe the bug**
We find a tricky issue that the controller may accidentally delete PVC even when the CassandraDataCenter is not being deleted. 

If a controller crashes and restarts, it may watch on any apiserver in a HA cluster. The watch is served by the apiserver’s cache without any freshness guarantee. If the apiserver happens to hold stale data in its watch cache, it may replay some stale events to the controller (and the controller has already received these events before the crash).

When the controller receives the previous events indicating a deletion (with deletion timestamp set), it will believe a deletion is ongoing and decides to delete the related PVC. The controller lists all related PVC using the tag:
```
"cassandra-operator.instaclustr.com/datacenter": instance.DataCenter,
"cassandra-operator.instaclustr.com/cluster":    instance.Cluster,
```
If the currently running CassandraDataCenter shares the same `DataCenter` and `Cluster` fields as the previously deleted one, the PVC belonging to the running one will be wrongly deleted.

**To Reproduce**
We met this issue after the following steps in a HA k8s cluster:
1. Create a CassandraDataCenter cdc1 with `deletePVCs=true`. The controller is talking to apiserver1 now.
2. Delete cdc1. Apiserver1 will send the `update` events with deletion timestamp to the controller and the controller will delete the related PVC of cdc1 after seeing the deletion timestamp. After that cdc1 is totally deleted.
3. Meanwhile, apiserver2 is partitioned so its watch cache stops at the moment that cdc1 is tagged with a deletion timestamp.
4. Create cdc2 with the same `DataCenter` and `Cluster` as before.
5. The controller crashes due to some node failures and restarts (or its follower becomes leader and starts to reconcile). This time the controller talks to the stale apiserver2. And now the partition at apiserver2 is gone.
6. The restarted controller receives the stale `update` events from apiserver2 that cdc1 has a deletion timestamp as apiserver2's watch cache still holds cdc1 with deletion timestamp. Since the `DataCenter` and `Cluster` fields for cdc1 and cdc2 are the same, the controller lists all PVC belonging to cdc2, and deletes them all.

**Expected behavior**
This can be avoided if the controller can differentiate the PVC belonging to different CassandraDataCenter instances even with the same `DataCenter` and `Cluster`. One solution is to use the UID of each CassandraDataCenter as one of the labels in `DataCenterAnnotations` and also use the UID to list PVC inside `finalizePVCs`. Each CassandraDataCenter should always have a different UID, so the controller will not mistakenly delete PVC which belongs to another CassandraDataCenter even receiving the replayed deletion.

**Additional context**
We are willing to file a patch for this issue.
This post https://github.com/kubernetes/kubernetes/issues/59848 discusses more details about the potential staleness in apiserver.

**Comment by smiklosovic** [comment]
Thank you @srteam2020 , these kind of issues might be spotted only after quite intensive and nontrivial usage and I am glad you are willing to return to us with your findings. Feel free to submit the patch, your help is appreciated.

Regards

**Comment by smiklosovic** [comment]
@srteam2020 any chance you work on this! I would love to see it fixed.

Thanks a lot.

**Comment by srteam2020** [comment]
@smiklosovic 
Yes! I will work on this. Getting busy recently so didn't have a chance to file a PR for this issue last week.

**Comment by smiklosovic** [comment]
thanks!
