### ISSUE TITLE
[BUG] Stale statefulset can be accidentally re-created when reading stale data from apiserver

### ISSUE THREAD

**Issue by srteam2020** [instaclustr/cassandra-operator#404]
**Describe the bug**
We find a tricky issue that the controller may accidentally recreate stale statefulset which belongs to a deleted CassandraDataCenter.

Similar to the situation in https://github.com/instaclustr/cassandra-operator/issues/402, the controller could experience a time-traveling by reading stale data from a slow apiserver after a restart. If a CassandraDataCenter cdc1 gets created and deleted, its statefulset (racks) should also be deleted. However, if another CassandraDataCenter cdc2 with the same `DataCenter ` and `Cluster` fields get recreated, the listOptions in `getStatefulSets ` could get the statefulset belonging to the previously deleted cdc1 when talking to a stale apiserver (and it tends to believe it belongs to `cdc2`):
```
sts := &v1.StatefulSetList{}

listOptions := []client.ListOption{
	client.InNamespace(rctx.cdc.Namespace),
	client.MatchingLabels{
		"cassandra-operator.instaclustr.com/datacenter": rctx.cdc.DataCenter,
		"cassandra-operator.instaclustr.com/cluster":    rctx.cdc.Cluster,
	},
}
```
The stale statefulset will later be created by `createOrUpdateStatefulSet`.

**To Reproduce**
We met this issue after the following steps in a HA k8s cluster:
1. Create a CassandraDataCenter cdc1 with a statefulset `rack1`. The controller is talking to apiserver1 now.
2. Delete `cdc1`, and `rack1` will also be automatically deleted.
3. Apiserver2 gets partitioned so it is unaware of the deletion of `rack1`
4. Create cdc2 with the same `DataCenter` and `Cluster` as before.
5. The controller restarts and its statefulset informer talks to the stale apiserver2.
6. When running `rctx.sets, err = getStatefulSets(rctx)`, the `list` will include the stale `rack1` statefulset as mentioned above. The stale statefulset will be created by the controller, which is unexpected.

**Expected behavior**
Stale statefulset should not be recreated by the controller, and the controller should be able to differentiate statefulsets belonging to different CassandraDataCenter. A solution is to use UID when listing statefulsets in `getStatefulSets`.

**Additional context**
In the recent https://github.com/instaclustr/cassandra-operator/pull/403 UID is already used to identify PVCs. So, to solve the issue and keep it consistent we may also use UID when listing statefulsets.
We are very willing to file a patch for this issue just as before. It should be a one-line change.

**Comment by smiklosovic** [comment]
Hi @srteam2020 ,

yes, please I am very willing to fix this problem. HA setups are tricky to get right and issues like these are harder to find, we have not run this in HA setup yet, I have to admin, no customer has specifically requested that so far so I am glad you dig deep here.
