### ISSUE TITLE
Rolling upgrade with image change & cassandra minor version change

### ISSUE THREAD

**Issue by liwang0513** [instaclustr/cassandra-operator#46]
A test to see if statefulset can handle this properly.

**Comment by smiklosovic** [comment]
This should be possible out of the box by Kubernetes itself by patching a statefulset and deleting pod

https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-out-a-canary
