### ISSUE TITLE
Can't install the cassandra chart

### ISSUE THREAD

**Issue by sneko** [instaclustr/cassandra-operator#52]
Hi,

Following your instructions I get the following error when trying to install Cassandra (not the operator):
`helm : Error: unable to recognize "": no matches for stable.instaclustr.com/, Kind=CassandraDataCenter`

I just followed the README, is it working for you?

Thank you 😃

**Comment by benbromhead** [comment]
Sorry for the delay on this, we changed the CRD kind as it was too generic (DataCenter vs CassandraDataCenter). See the above mentioned PR which should fix this (I confirmed the helm charts now work in minikube).

Note there are now new values to configure in the Values.yaml file for the Cassandra helm package. Make sure you review.

**Comment by sneko** [comment]
Thank you for the update @benbromhead 😃 

At this time I'm not available to test it, I used as fallback the incubated Helm Chart (https://github.com/kubernetes/charts/tree/master/incubator/cassandra) to use some tools in time, but I prefer to use your operator 😃 . So as soon as I have time I will try again 👍 

Feel free to close this issue if someone confirms that's the merged works well.

Thanks again for your work!

**Comment by benbromhead** [comment]
Issue reviewed and merged
