### ISSUE TITLE
Tag `cassandra` image with Cassandra version

### ISSUE THREAD

**Issue by zegelin** [instaclustr/cassandra-operator#57]
Curently, `build` & `build-all` tag images with the repo short hash & `latest`. This is useful for development.

Ideally the Cassandra image should be tagged with the version of C* it represents, e.g. `3.2.11`.
This makes it obvious what version is contained within, and will be necissary once we need to support multiple C* versions.

**Comment by benbromhead** [comment]
Agreed, once we leave pre-alpha/alpha we'll need to figure out naming

**Comment by alourie** [comment]
We're already tagging it with Cassandra version, but I've also added version tags in #306. So we now will have `:latest`, `:<cassandra-version>`, `:<operator-version>` and `:<cassandra-version>-<operator version>`, so that we are always able to pick a specific version of the container image.
