### ISSUE TITLE
Project release is not ready

### ISSUE THREAD

**Issue by liwang-pivotal** [instaclustr/cassandra-operator#64]
Looks like we are not ready to give out a project [v1.0.0 release](https://github.com/instaclustr/cassandra-operator/releases) since we still have some bugs to be tackled.

**Comment by benbromhead** [comment]
Ah whoops, not sure what went on there. I think that was just a release of the backup agent? I'll look into it

**Comment by benbromhead** [comment]
Releases have been pulled
