### ISSUE TITLE
Fork backup tool to separate repository

### ISSUE THREAD

**Issue by lyubentt** [instaclustr/cassandra-operator#66]
The backup tool that is part of the toolbelt of the operator is getting some attention outside of the kubernetes functionality being provided with the operator project. At this point the backup module presents enough functionality that it could be a stand-alone project.

The important step is to make  sure that the cassandra-operator remains unaffected. A somewhat clean way of proceeding here would be to segregate the backup module and add it back as a dependency that can be used by cassandra-operator. 

To keep the backup module stable an initial release would be required. Post this release further breaking changes could be introduced to the `master` branch whilst a 1.0.0 branch could be maintained for bug fixing. This approach will allow for the cassandra-operator to introduce breaking changes on backup's master branch if necessary.

**Comment by benbromhead** [comment]
See https://github.com/instaclustr/cassandra-backup
