### ISSUE TITLE
Failed to pull image "gcr.io/cassandra-operator/cassandra-sidecar-dev"

### ISSUE THREAD

**Issue by xek** [instaclustr/cassandra-operator#69]
I see you uploaded almost everything to gcr.io, but cassandra-sidecar is missing.
After installing the operator and starting the cluster I have this error:

```Failed to pull image "gcr.io/cassandra-operator/cassandra-sidecar-dev": rpc error: code = Unknown desc = unauthorized: authentication required```

**Comment by benbromhead** [comment]
Hi Xek

Thanks for the update, at the moment builds are failing due to our pivotal test cluster being out of action, this means sidecar images are not being published. 

I'm pulling out pivotal tests from circleci until the test infra issues are resolved.

Ben

**Comment by benbromhead** [comment]
And also I think we didn't include in the publish script. See #71

**Comment by benbromhead** [comment]
Ok should be fixed now. Also we have changed the build system to push non "-dev" based images as well for builds from the master branch. 

You should start using the non-dev images for your testing. So `gcr.io/cassandra-operator/cassandra-sidecar` should be available.

**Comment by xek** [comment]
Where do I specify this image?

I see it is hardcoded here: https://github.com/instaclustr/cassandra-operator/blob/b46ef90b049d107da926fff2c18583ce93fbcb1a/java/operator/src/main/java/com/instaclustr/cassandra/operator/service/ControllerService.java#L259

So this is probably where I got it from by following examples from the documentation.

**Comment by benbromhead** [comment]
Ah right ok, we need to make the sidecar image name part of the Cassandra CRD.

Thanks for pointing that out.

**Comment by benbromhead** [comment]
You can now specify the side car image via the CRD :)
