### ISSUE TITLE
Multi-AZ topologies

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#78]
The behavior of Kubernetes scheduling pods across different failure domains is somewhat undefined and hard to control. See for details:

https://github.com/kubernetes/kubernetes/issues/41598 
https://github.com/kubernetes/kubernetes/pull/44798
https://github.com/kubernetes/community/pull/1857

Despite recent fixes to statefulsets, we still cannot inject failure domain information into the pods. So we still need to do a statefulset per failure domain.

This also gives us some flexability in tolerating outages and nodes being down in a single SS.

**Comment by eriksw** [comment]
Kubernetes 3.11 has been out for a while. Is there any update on this?

**Comment by alourie** [comment]
Implemented with #192
