### ISSUE TITLE
Issue when creating backup snapshot

### ISSUE THREAD

**Issue by benbromhead** [instaclustr/cassandra-operator#83]
23:13:20.114 [BackupControllerService] ERROR o.g.j.m.i.WriterInterceptorExecutor - MessageBodyWriter not found for media type=application/json, type=class com.instaclustr.backup.BackupArguments, genericType=class com.instaclustr.backup.BackupArguments.

**Comment by benbromhead** [comment]
Running on latest version of master, does not appear to get this exception?

14:08:58.701 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Creating Custom Resource Definition cassandra-datacenters.stable.instaclustr.com
14:08:58.738 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Custom Resource Definition cassandra-datacenters.stable.instaclustr.com already exists.
14:08:58.741 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Creating Custom Resource Definition cassandra-clusters.stable.instaclustr.com
14:08:58.750 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Custom Resource Definition cassandra-clusters.stable.instaclustr.com already exists.
14:08:58.753 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Creating Custom Resource Definition cassandra-backups.stable.instaclustr.com
14:08:58.760 [main] INFO  c.i.c.o.p.o.CreateCustomResourceDefinitions - Custom Resource Definition cassandra-backups.stable.instaclustr.com already exists.
14:08:58.899 [main] INFO  com.instaclustr.guava.Application - Services to start: [ControllerService [NEW], GarbageCollectorService [NEW], CassandraHealthCheckService [NEW], BackupControllerService [NEW], WatchService(Cluster) [NEW], WatchService(DataCenter) [NEW], WatchService(V1beta2StatefulSet) [NEW], WatchService(V1ConfigMap) [NEW], WatchService(Backup) [NEW]]
14:08:58.900 [main] INFO  com.instaclustr.guava.Application - Starting services.
14:08:58.933 [main] INFO  com.instaclustr.guava.Application - Successfully started all services.
14:08:59.075 [ControllerService] INFO  c.i.c.o.service.ControllerService - Reconciling Data Center.
14:09:04.435 [WatchService(Backup)] INFO  c.i.c.o.s.BackupControllerService - Received BackupWatchEvent com.instaclustr.cassandra.operator.event.BackupWatchEvent$Added@24782bfd.
14:09:04.435 [BackupControllerService] INFO  c.i.c.o.s.BackupControllerService - Reconciling Backup.

@liwang-pivotal can you make sure you are on the latest commit? Also the pull policy for the operator and cassandra to Always. This will make sure you are running the latest.

**Comment by liwang-pivotal** [comment]
@benbromhead the `imagePullPolicy` I used is `Always` to make sure avoiding the version issue. I highly suspect that the images on gcr is not latest as yours. The image I'm using is copied from helm:
operatorImage: `gcr.io/cassandra-operator/cassandra-operator:latest`
cassandraImage: `gcr.io/cassandra-operator/cassandra:latest`
sidecarImage: `gcr.io/cassandra-operator/cassandra-sidecar:latest`

**Comment by benbromhead** [comment]
Have not seen issue again, appeared to be old image problem
