### ISSUE TITLE
(?) Memory continuosly increasing

### ISSUE THREAD

**Issue by sneko** [instaclustr/cassandra-operator#93]
Hi,

I said in my previous issue I will wait for a more improved operator to be able to use Jaeger easily... So I deleted my Cassandra cluster instance but left the operator.

In the meantime one of my nodes has crashed so I looked for the cause of the problem. Looking at all my pods/statefulsets/deployments metrics I noticed that the Cassandra operator memory had increased over time:
![image](https://user-images.githubusercontent.com/8195958/44809772-fc0b9e80-abcf-11e8-9200-03bfd0e1c1ed.png)

And that's the only one doing that. I "suspect" it for crashing its host node. For sure I could set request and limit resources to kill the pod before it eats all the node memory but that doesn't explain the consumption graph over time.

Moreover, currently the operator pod memory is stable around 200MB... 😄 

I can't tell for sure there is a memory leak inside the operator, but I wanted to share with you this "experience".

I would have loved to also share logs of the operator but I don't have them (I'm really sorry).

Have a good day,

**Comment by zegelin** [comment]
@sneko thanks for the bug report. I'll keep an eye out for memory usage problems.
Just to confirm, you have the operator running on the cluster but no Cassandra DC created/managed through it, right? So it should be idle.

**Comment by sneko** [comment]
@zegelin yes there was no C* DC anymore

**Comment by smiklosovic** [comment]
Operator was rewritten into Go so this issue is not relevant anymore.
